#
# Основная команда для перезагрузки плагина - /exblocker
# Право на использование команды - explosionsblocker.reload
#
# Основные настройки запретов
settings:
  # Настройки для криперов
  creeper:
    # Нужно ли отключать взрыв блоков
    block-explosion: true
    # Нужно ли отключать урон мобам/игрокам которых взорвали
    block-damage: true
    # Добавить эффект взрыва на место крипера?
    effect: true
    # Проиграть ли звук взрыва?
    sound: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2
  # Настройки динамита
  tnt:
    # Нужно ли отключать взрыв блоков
    block-explosion: true
    # Нужно ли отключать урон мобам/игрокам которые были в радиус взрыва?
    block-damage: true
    # Добавить эффект взрыва на место тнт?
    effect: true
    # Проиграть ли звук взрыва?
    sound: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2
  # Настройки динамита в вагонетке
  tnt-in-cart:
    # Нужно ли отключать взрыв блоков
    block-explosion: true
    # Нужно ли отключать урон мобам/игрокам которых взорвали
    block-damage: true
    # Добавить эффект взрыва на место вагонетки с динамитом?
    effect: true
    # Проиграть ли звук взрыва?
    sound: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2
  # Настройки визера
  wither:
    # Нужно ли отключать урон мобам/игрокам которых визер атакует?
    block-damage: true
    # Отключить ли ломание блоков для визера?
    block-blocks-breaking: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2
  # Настройки визера при активации (После спавна визера он еще несколько секунд неактивен)
  wither-activate:
    # Нужно ли отключать взрыв блоков
    block-explosion: true
    # Добавить эффект взрыва на место визера?
    effect: true
    # Проиграть ли звук взрыва?
    sound: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2
  # Настройки голов которыми стреляется визер
  wither-heads:
    # Нужно ли отключать взрыв блоков
    block-explosion: true
    # Нужно ли отключать урон мобам/игрокам в которых прилетела голова визера?
    block-damage: true
    # Добавить эффект взрыва на место попадания головы?
    effect: true
    # Проиграть ли звук взрыва?
    sound: true
    # Миры в которых будет отключаться
    blocked-worlds:
      - test_world
      - test_world2

# Сообщения
messages:
  # Сообщение при перезагрузке плагина
  reload-message: '&aПлагин ExplosionsBlocker успешно перезагружен.'
  # Сообщения если не хватает прав на использование команды
  no-permission: '&cИзвини, но у тебя не хватает прав на использование данной команды.'