name: ExplosionsHandler
version: '${project.version}'
main: graundbreaking.explosionshandler.ExplosionsBlocker
author: graundbreaking
description: Handle all types of explosions

commands:
  exhandler: {}

permissions:
  explosionshandler.reload:
    default: op
    description: Allows you to reload the plugin

  explosionshandler.updates:
    default: op
    description: Allows you see updates notifications